import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

interface AIDisclaimerProps {
    variant?: 'inline' | 'banner' | 'compact';
    style?: any;
}

/**
 * AI Disclaimer Component
 * Displays a professional disclaimer about AI-generated content
 * 
 * Usage:
 * <AIDisclaimer variant="banner" />
 * <AIDisclaimer variant="inline" />
 * <AIDisclaimer variant="compact" />
 */
export const AIDisclaimer: React.FC<AIDisclaimerProps> = ({
    variant = 'inline',
    style
}) => {
    if (variant === 'compact') {
        return (
            <View style={[styles.compactContainer, style]}>
                <Ionicons name="information-circle-outline" size={14} color="#6B7280" />
                <Text style={styles.compactText}>
                    This content is generated using artificial intelligence. While we strive for accuracy, AI may occasionally produce incorrect or incomplete information. Please verify critical details from authoritative sources.
                </Text>
            </View>
        );
    }

    if (variant === 'banner') {
        return (
            <View style={[styles.bannerContainer, style]}>
                <View style={styles.bannerIconContainer}>
                    <Ionicons name="sparkles" size={20} color="#6366F1" />
                </View>
                <View style={styles.bannerContent}>
                    <Text style={styles.bannerTitle}>AI-Powered Content</Text>
                    <Text style={styles.bannerText}>
                        This content is generated using artificial intelligence. While we strive for accuracy,
                        AI may occasionally produce incorrect or incomplete information. Please verify
                        critical details from authoritative sources.
                    </Text>
                </View>
            </View>
        );
    }

    // Default: inline variant
    return (
        <View style={[styles.inlineContainer, style]}>
            <View style={styles.inlineHeader}>
                <Ionicons name="alert-circle-outline" size={18} color="#F59E0B" />
                <Text style={styles.inlineTitle}>AI Disclaimer</Text>
            </View>
            <Text style={styles.inlineText}>
                Content generated by AI may contain inaccuracies or hallucinations.
                Always cross-verify important information with reliable sources before making decisions.
            </Text>
        </View>
    );
};

const styles = StyleSheet.create({
    // Compact variant
    compactContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    compactText: {
        fontSize: 12,
        color: '#6B7280',
        fontStyle: 'italic',
    },

    // Banner variant
    bannerContainer: {
        flexDirection: 'row',
        backgroundColor: '#EEF2FF',
        borderRadius: 12,
        padding: 14,
        marginVertical: 8,
        borderWidth: 1,
        borderColor: '#C7D2FE',
    },
    bannerIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 10,
        backgroundColor: '#E0E7FF',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    bannerContent: {
        flex: 1,
    },
    bannerTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#4338CA',
        marginBottom: 4,
    },
    bannerText: {
        fontSize: 12,
        color: '#4B5563',
        lineHeight: 18,
    },

    // Inline variant
    inlineContainer: {
        backgroundColor: '#FFFBEB',
        borderRadius: 10,
        padding: 12,
        marginVertical: 8,
        borderWidth: 1,
        borderColor: '#FDE68A',
    },
    inlineHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 6,
    },
    inlineTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#B45309',
    },
    inlineText: {
        fontSize: 12,
        color: '#92400E',
        lineHeight: 18,
    },
});

export default AIDisclaimer;
